config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, DeviseUser.route_options

  devise_scope :user do
    get 'forgot', to: 'devise/passwords#new', as: :forgot
    get 'sign-in', to: 'devise/sessions#new', as: :sign_in
    get 'sign-out', to: 'devise/sessions#destroy', as: :sign_out
    get 'sign-up', to: 'devise/registrations#new', as: :sign_up
  end

  get :ping, to: 'ping#show'
  get :today, to: 'today#show'

  get 'pto', to: 'pto#index'
  get 'pto/:year', to: 'pto#show', as: :pto_report

  get 'work_weeks/:target', to: 'work_weeks#show', as: :work_week

  patch 'work_days/:id', to: 'work_days#update'

  get :account, to: 'account#show'

  get :upgrade, to: 'upgrade#show'
  post :upgrade, to: 'upgrade#create'
  get :thanks, to: 'thanks#show'

  Sidekiq::Web.use(Rack::Auth::Basic, &SidekiqCreds.checker)
  mount Sidekiq::Web, at: '/sidekiq'

  namespace :admin do
    get :users, to: 'users#index'
  end

  root to: redirect('/today')
end

app/controllers/pto_controller.rb
class PtoController < AuthenticatedController
  expose(:pto_report) { PtoReport.generate_for(current_user, params[:year]) }

  def index
    year = Time.zone.today.year
    redirect_to pto_report_path(year)
  end
end

app/views/pto/show.html.haml
#pto
  %nav
    .top
      = link_to "<", pto_report_path(pto_report.prev_year), class: "button"
      %p= pto_report.year
      = link_to ">", pto_report_path(pto_report.next_year), class: "button"
    .totals
      %div
        %h1= pto_report.ytd_total
        %p ytd
      %div
        %h1= pto_report.grand_total
        %p total
  .list
    %ul
      - pto_report.entries.each do |entry|
        %li
          = link_to entry.listing, work_week_path(entry.target)